### ISSUE TITLE
Bug: Delete Function

### ISSUE THREAD

**Issue by s-arika** [mskuybeda/my-note#1]
Clicking on the delete function does not clear the content of the textarea. It produces this error: 
<img width="1440" alt="Screen Shot 2019-09-16 at 9 33 52 PM" src="https://user-images.githubusercontent.com/28491962/65004277-d4b26d00-d8c9-11e9-8dd5-381dd019842e.png">

**Comment by mskuybeda** [comment]
Thanks for the fix. I missed it when was coding.
